apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: stage
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: old
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: nginx-configuration
          volumeMounts:
            - name: nginx-configuration
              mountPath: usr/share/nginx/html
      volumes:
        - name: nginx-configuration
          configMap:
            name: nginx-configuration
            items:
              - key: index.html
                path: index.html
